language: generic
sudo: required
addons:
  ssh_known_hosts:
    - $HOST
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh $HOST_USER@$HOST 'bash ./deploy.sh'
  on:
    branch: master
